### ISSUE TITLE
Not Completed Assignment

### ISSUE THREAD

**Issue by nk180010** [sahilparmar4/Movie_Recommendation#1]
your assignment is not completed , because not have prediction of movie. you just only add movie recommendation.
Bro read again assignment statement and work on it.

**Comment by sahilparmar4** [comment]
I forgot to explain what is recommendation system?

But what can I do, if you don't know what is  content based recommendation
system?

**Comment by nk180010** [comment]
Brother i think you forget , same solution attempt in goeduhub. Mam was said this is not completed

**Comment by sahilparmar4** [comment]
Because your website is not working. I  looking for some reference, then I
saw your answer, but it showed nothing. (404 not found) that's why mam told
you to incomplete task.

**Comment by nk180010** [comment]
![image](https://user-images.githubusercontent.com/69339602/125922908-0b1abb61-1285-470a-a913-54042f1ea706.png)
![image](https://user-images.githubusercontent.com/69339602/125923303-9475e771-66c6-4741-89b5-fef50fc8dc47.png)
my is working , check your , i check yesterday site is on but not working after search movie name your site. 
check it herokuapp log !

**Comment by sahilparmar4** [comment]
See, mine is also working. Mam was also commented in my post. Mam is not
blind without checking anything she is going to do comment in everyone's
post.

You should write proper spelling. If it is, it will give you recommendation
otherwise internal server error.

So without checking properly, you don't have rights to write any thing.

**Comment by nk180010** [comment]
so ja bhai , hadd h yrr tre be screeen shot bej rha hu phir be bol rha h ke working h. chal maan la spelling issue h no problem , but logic issue to nahi h na.

**Comment by nk180010** [comment]
![image](https://user-images.githubusercontent.com/69339602/125926814-ace5151e-a8b3-4a78-8461-e185b0da7ea9.png)
dekh
